language: java 
dist: trusty
addons:
  sonarqube:
    token:
      secure: 737dc0e2db4d75453dbff744d80ba06b23918eeb # encrypted value of your token
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
notifications:
  slack: sungshinit:Fk0Ykxvm9qcwpcqFg4vI8obF
